language: php

php:
    - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' ]]; then export SYMFONY__ALGOLIA_ENABLED="1"; fi;
    - composer self-update
    - composer install

script:
    - ./vendor/bin/sculpin generate --env=prod --url="https://developers.shopware.com"
    - ./contrib/package_plugins.sh

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./deploy.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: output_prod
    target_branch: gh-pages
    fqdn: developers.shopware.com
    name: shopwareBot
    email: entwicklung@shopware.de
    on:
        branch: master